### ISSUE TITLE
cannot find anythig in english

### ISSUE THREAD

**Issue by MIaha3278** [cosad3s/postleaks#1]
Hi! I try to use you script but when I place a requests in english there is nothing found and when I use Russian its finds some. what can I do?

**Comment by cosad3s** [comment]
Can you provide an example to help me to reproduce the problem ?

**Comment by ResistanceIsUseless** [comment]
I think they are correct. I tried a bunch of generic keywords and it feels like broad searching isn't working anymore.

```
➜  Tools postleaks -k password      
[*] Looking for data in Postman.com
[*] Searching for requests IDs
[-] Error: No data found
➜  Tools postleaks -k "github_token"
[*] Looking for data in Postman.com
[*] Searching for requests IDs
[-] Error: No data found
➜  Tools postleaks -k "username"    
[*] Looking for data in Postman.com
[*] Searching for requests IDs
[-] Error: No data found
➜  Tools postleaks -k "Apple.com"
[*] Looking for data in Postman.com
[*] Searching for requests IDs
[-] Error: No data found
➜  Tools postleaks -k "github.com"
[*] Looking for data in Postman.com
[*] Searching for requests IDs
[-] Error: No data found
```

**Comment by cosad3s** [comment]
Thanks, I will investigate

**Comment by cosad3s** [comment]
Ok, I have identified that Postman.com introduced a limitation about the number of returned results.
I will try to find a workaround if possible.

*For example, for `apple.com`, even with the UI at [https://www.postman.com/search?q=apple.com&scope=public&type=request](https://www.postman.com/search?q=apple.com&scope=public&type=request), it is not possible to browse more than 300 anymore.*

I added a limitation due to Postman.com restriction.

**Comment by cosad3s** [comment]
Thanks @ResistanceIsUseless @MIaha3278 !

**Comment by ResistanceIsUseless** [comment]
thank you @cosad3s, thanks for a great tool!
